# Generated by Django 3.1.7 on 2021-03-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20210310_1145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-post_date']},
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, default='C:\\Users\\jlwil\\blogproject\\blogproject\\blogs', upload_to='blogs'),
        ),
    ]
