# Generated by Django 3.1.7 on 2021-03-10 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_auto_20210310_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, default='\\blogs\\tempdefault.jpg', upload_to='blogs'),
        ),
    ]
