# Generated by Django 3.1.7 on 2021-06-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0013_auto_20210310_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_author',
            field=models.CharField(default='Joseph', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, default='tempdefault.jpg', upload_to='blogs'),
        ),
    ]
